packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"
  
catalog:
  eslint: ^9.21.0
  prettier: ^3.4.2
  tailwindcss: ^4.0.9
  typescript: ^5.7.3
  zod: ^3.24.1
  
catalogs:
  react19:
   react: ^19.0.0
   react-dom: ^19.0.0
   "@types/react": ^19.0.10
   "@types/react-dom": ^19.0.4