packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  eslint: ^9.22.0
  typescript: ^5.8.2
  "@types/node": ^22.13.9
  
catalogs:
  react19:
   react: ^19.0.0
   react-dom: ^19.0.0
   "@types/react": 19.0.10
   "@types/react-dom": 19.0.4